persistence:
  defaultStore: postgres-default
  visibilityStore: postgres-visibility
  datastores:
    postgres-default:
      sql:
        pluginName: "postgres"
        databaseName: "temporal"
        connectAddr: "localhost:5432"
        connectProtocol: "tcp"
        user: "postgres"
        password: "yourpassword"
        maxConns: 20
    postgres-visibility:
      sql:
        pluginName: "postgres"
        databaseName: "temporal_visibility"
        connectAddr: "localhost:5432"
        connectProtocol: "tcp"
        user: "postgres"
        password: "yourpassword"
        maxConns: 10

# CREATE DATABASE temporal;
#CREATE DATABASE temporal_visibility;
# temporal server start --config config.yaml --namespace remindme
# temporal sql-tool setup-schema -p postgres -d temporal -u postgres -pw yourpassword
#temporal sql-tool setup-schema -p postgres -d temporal_visibility -u postgres -pw yourpassword --visibility
# temporal namespace create remindme