"""Add calendar integrations

Revision ID: 27a3e92ba4d0
Revises: ca646d97b8c8
Create Date: 2025-05-01 18:02:46.815755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27a3e92ba4d0'
down_revision: Union[str, None] = 'ca646d97b8c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_integrations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('caldav_url', sa.Text(), nullable=True),
    sa.Column('login', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('last_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('reminders', sa.Column('calendar_event_id', sa.String(length=255), nullable=True))
    op.add_column('reminders', sa.Column('calendar_integration_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'reminders', 'calendar_integrations', ['calendar_integration_id'], ['id'], ondelete='SET NULL')
    op.drop_column('users', 'calendar_integration_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('calendar_integration_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reminders', type_='foreignkey')
    op.drop_column('reminders', 'calendar_integration_id')
    op.drop_column('reminders', 'calendar_event_id')
    op.drop_table('calendar_integrations')
    # ### end Alembic commands ###
