"""User timezone offset

Revision ID: 393612152ff9
Revises: f35b59b53d5e
Create Date: 2025-04-20 23:27:58.041707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '393612152ff9'
down_revision: Union[str, None] = 'f35b59b53d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('timezone_offset', sa.Integer(), nullable=True))
    op.drop_column('users', 'timezone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('timezone', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('users', 'timezone_offset')
    # ### end Alembic commands ###
