"""Neuro Image Rate

Revision ID: 3ba879bcab3c
Revises: e69e2f39be18
Create Date: 2025-04-25 20:00:58.907959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ba879bcab3c'
down_revision: Union[str, None] = 'e69e2f39be18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('neuro_images', sa.Column('rate', sa.Enum('GOOD', 'NEUTRAL', 'BAD', name='imagerate'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('neuro_images', 'rate')
    # ### end Alembic commands ###
